import { NextResponse } from "next/server";
import { auth, IS_DEV } from "@/auth";
import { getTasksCollection } from "@/lib/mongodb";

const MARCUS = {
  email: "marcus.silva@gruporoncador.com.br",
  name: "Marcus Silva",
};

const SEED_TASKS = [
  {
    id: "t_seed_01",
    title: "API de Integrações — Entender iatfapidev.roncador.com.br",
    description: "Análise e mapeamento da API de desenvolvimento IATF para entender endpoints disponíveis e estrutura de autenticação.",
    status: "concluido",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "API de Integrações",
    category: "Desenvolvimento",
    situacaoAtual: "API mapeada e documentada internamente.",
    impeditivo: "",
    dueDate: "2026-06-03",
    dataEntrega: "2026-06-03",
    dataConclusao: "2026-06-03",
    tempoEstimado: 4,
    tempoPrevisto: 4,
    progress: 100,
    subtasks: [],
    createdAt: "2026-06-03",
    updatedAt: "2026-06-03",
  },
  {
    id: "t_seed_02",
    title: "Zendesk — Entender campos para endpoints (reunião)",
    description: "Reunião com Jackson para mapear os campos necessários para integração dos endpoints do Zendesk.",
    status: "concluido",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Zendesk",
    category: "Reunião",
    situacaoAtual: "Jackson vai criar docs com os campos necessários.",
    impeditivo: "",
    dueDate: "2026-06-03",
    dataEntrega: "2026-06-03",
    dataConclusao: "2026-06-03",
    tempoEstimado: 2,
    tempoPrevisto: 2,
    progress: 100,
    subtasks: [],
    createdAt: "2026-06-03",
    updatedAt: "2026-06-03",
  },
  {
    id: "t_seed_03",
    title: "IATF — Criar endpoints API middleware",
    description: "Desenvolvimento dos endpoints do middleware de integração entre sistemas internos e a API IATF.",
    status: "em_andamento",
    priority: "alta",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "IATF",
    category: "Desenvolvimento",
    situacaoAtual: "Aguardando validação do Rodrigo para prosseguir com os testes.",
    impeditivo: "Não conseguem acessar a API no ambiente de homologação.",
    dueDate: "2026-06-16",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 16,
    tempoPrevisto: 20,
    progress: 90,
    subtasks: [],
    createdAt: "2026-06-05",
    updatedAt: "2026-06-16",
  },
  {
    id: "t_seed_04",
    title: "Hub Roncador — Analisar repositório e definir escopo v2",
    description: "Análise do repositório github.com/Grupo-Roncador/hub-roncador para levantamento de requisitos e definição do escopo da versão 2.",
    status: "pendente",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Hub Roncador",
    category: "Desenvolvimento",
    situacaoAtual: "Definir escopo v2 com time antes de iniciar.",
    impeditivo: "",
    dueDate: "2026-06-16",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 8,
    tempoPrevisto: 0,
    progress: 0,
    subtasks: [],
    createdAt: "2026-06-10",
    updatedAt: "2026-06-10",
  },
  {
    id: "t_seed_05",
    title: "Zendesk — Desenvolver formulários para Renan",
    description: "Desenvolvimento dos formulários de atendimento no Zendesk conforme especificação do Renan.",
    status: "em_andamento",
    priority: "alta",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Zendesk",
    category: "Desenvolvimento",
    situacaoAtual: "Call agendada para 16/06 às 16h para alinhamento final.",
    impeditivo: "Aguardando Jackson enviar documentação com os campos dos endpoints.",
    dueDate: "2026-06-16",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 12,
    tempoPrevisto: 16,
    progress: 40,
    subtasks: [],
    createdAt: "2026-06-09",
    updatedAt: "2026-06-16",
  },
  {
    id: "t_seed_06",
    title: "Site Grupo Roncador — Credenciais e apresentação para Allan",
    description: "Reunião com Allan para entrega das credenciais de acesso ao site do Grupo Roncador e apresentação da estrutura do projeto.",
    status: "concluido",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Site Grupo Roncador",
    category: "Reunião",
    situacaoAtual: "Credenciais entregues e apresentação realizada com sucesso.",
    impeditivo: "",
    dueDate: "2026-06-16",
    dataEntrega: "2026-06-16",
    dataConclusao: "2026-06-16",
    tempoEstimado: 1,
    tempoPrevisto: 1,
    progress: 100,
    subtasks: [],
    createdAt: "2026-06-16",
    updatedAt: "2026-06-16",
  },
  {
    id: "t_seed_07",
    title: "API de Integrações — Servidor AWS para Zendesk/IATF",
    description: "Provisionar e configurar servidor AWS para hospedar os serviços de integração do Zendesk e IATF em produção.",
    status: "em_andamento",
    priority: "alta",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "API de Integrações",
    category: "Infraestrutura",
    situacaoAtual: "Aguardando Alberto liberar acesso e confirmar regras de firewall do LOGIX.",
    impeditivo: "Regras de firewall do LOGIX bloqueando comunicação entre servidores.",
    dueDate: "2026-06-15",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 8,
    tempoPrevisto: 12,
    progress: 90,
    subtasks: [],
    createdAt: "2026-06-12",
    updatedAt: "2026-06-15",
  },
  {
    id: "t_seed_08",
    title: "Sistema de Acompanhamento de Tarefas — Desenvolvimento",
    description: "Desenvolvimento do sistema interno de acompanhamento de tarefas operacionais para substituir planilhas manuais. Next.js + MongoDB + NextAuth.",
    status: "em_andamento",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Infraestrutura Interna",
    category: "Desenvolvimento",
    situacaoAtual: "Sistema funcional com dashboard, tabela, relatórios e autenticação Microsoft.",
    impeditivo: "",
    dueDate: "2026-06-30",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 20,
    tempoPrevisto: 24,
    progress: 80,
    subtasks: [
      { id: "st_01", title: "Estrutura base Next.js + Tailwind", status: "concluido" },
      { id: "st_02", title: "Autenticação Microsoft (NextAuth)", status: "concluido" },
      { id: "st_03", title: "Integração MongoDB", status: "concluido" },
      { id: "st_04", title: "Dashboard e gráficos", status: "concluido" },
      { id: "st_05", title: "Tabela de tarefas com filtros", status: "concluido" },
      { id: "st_06", title: "Página de relatórios + exportação Excel", status: "concluido" },
      { id: "st_07", title: "Seção de monitoramento de sistemas", status: "pendente" },
    ],
    createdAt: "2026-06-01",
    updatedAt: "2026-06-16",
  },
  {
    id: "t_seed_09",
    title: "Organização dos relatórios gerenciais",
    description: "Estruturação e padronização dos relatórios gerenciais mensais de Business Intelligence para apresentação à liderança.",
    status: "em_andamento",
    priority: "media",
    assignedTo: MARCUS.email,
    assignedToName: MARCUS.name,
    projeto: "Business Intelligence",
    category: "Documentação",
    situacaoAtual: "Relatórios de maio finalizados. Trabalhando no template de junho.",
    impeditivo: "",
    dueDate: "2026-06-30",
    dataEntrega: "",
    dataConclusao: "",
    tempoEstimado: 10,
    tempoPrevisto: 10,
    progress: 50,
    subtasks: [],
    createdAt: "2026-06-01",
    updatedAt: "2026-06-14",
  },
];

export async function POST() {
  try {
    const session = await auth();
    console.log("Session:", session);
    if (!session?.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const isAdmin = (session.user as any).isAdmin ?? false;
    if (!isAdmin && !IS_DEV) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const collection = await getTasksCollection();

    await collection.deleteMany({});

    const docs = SEED_TASKS.map((t) => ({ _id: t.id, ...t }));
    await collection.insertMany(docs as any);

    return NextResponse.json({ ok: true, inserted: SEED_TASKS.length });
  } catch (err) {
    console.error("[POST /api/tasks/seed]", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
